set guicursor=
set termguicolors
set relativenumber
set nu
set scrolloff=8
set incsearch
set nohlsearch
set hidden
set noerrorbells
set smartindent
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set signcolumn=yes
set isfname+=@-@
set colorcolumn=80
set cmdheight=2
set updatetime=50
set shortmess+=c
